'use client';

import Navbar from '@/features/layout/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Titillium_Web } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { Provider } from 'react-redux';

import { PersistGate } from 'redux-persist/integration/react';
import { persistor, store } from '@/services/store';

const titillium = Titillium_Web({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={titillium.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ThemeProvider attribute='class'>
              <Navbar />
              {children}
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
